openapi: 3.0.0
info:
  title: Airports API
  description: Get all your airport data here https://raw.githubusercontent.com/WhiteHatLearningProducts/airports/master/airportsData.json 
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: if you are using NodeJS your dev port might be 3000
  - url: http://localhost:8080
    description: if you are using Spring your dev port will be 8080
  - url: https://airports-api.whitehatcoaches.org.uk
    description: this is the production baseURL
components:
  schemas:
    Airport:
      properties:
        icao:
          type: string
        iata:
          type: string
        name:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        elevation:
          type: integer
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
        tz:
          type: string
      required: 
        - icao
        - iata
        - name
        - city
        - state
        - country
        - elevation
        - lat
        - lon
        - tz
      example:
        icao: "00AK"
        iata: ""
        name: "Lowell Field"
        city: "Anchor Point"
        state: "Alaska"
        country: "US"
        elevation: 450
        lat: 59.94919968
        lon: -151.695999146
        tz: "America/Anchorage"
paths:
  /airports:
    get:
      summary: Reads all airports
      description: |
        Returns all the airports

        ![airport](https://twistedsifter.com/wp-content/uploads/2014/11/mexico-city-international-airport-drone-video.jpg)

        Including images!
      responses:
        200:
          description: status ok - returns an array of JSON objects that represent each airport
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        302:
          description: moved temporarily 
        404: 
          description: not found 
        500: 
          description: internal server error  
    post:
        summary: Creates 
        description:  Adds latest airport to the existing list of airports
        requestBody: 
          required: true
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Airport'
        responses: 
          200:
            description: status ok - airport was added
          302:
            description: moved temporarily 
          404: 
            description: not found 
          500: 
            description: internal server error  
  /airports/{icao}:
    get: 
        summary: Reads one airport
        description: Returns one specific airport
        parameters: 
        - in: path
          required: true 
          name: icao 
          description: Unique airport ID
          schema: 
            required:
              - icao
            properties:
              icao: 
               type: string
        responses:
          200:
            description: status ok - returns one JSON object that represent that airport
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Airport'
          302:
            description: moved temporarily 
          404: 
            description: not found 
          500: 
            description: internal server error  
    put:
        summary: Updates
        parameters: 
        - in: path
          required: true 
          name: icao 
          description: Unique airport ID
          schema: 
            required:
              - icao
            properties:
              icao: 
               type: string
        description:  Updates an airport in the existing list of airports
        requestBody: 
          required: true
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Airport'
        responses: 
          200:
            description: status ok - airport was updated
          302:
            description: moved temporarily 
          404: 
            description: not found 
          500: 
            description: internal server error  
    delete:
        summary: Deletes
        parameters: 
        - in: path
          required: true 
          name: icao 
          description: Unique airport ID
          schema: 
            required:
              - icao
            properties:
              icao: 
               type: string
        description:  Deletes an airport from the existing list of airports
        responses: 
          200:
            description: status ok - airport was deleted
          302:
            description: moved temporarily 
          404: 
            description: not found 
          500: 
            description: internal server error 
  